server:
  port: 8080

logging:
  level:
    root: info
    org.hibernate.SQL: error
    org.springframework: info
    org.springframework.web: info
    springframework.web.client.RestTemplate: info
    org.springframework.security: info
    com.example: debug

spring:
  #SQLLITE
  #datasource:
    #url: jdbc:sqlite:C:\software\SQLiteDatabaseBrowserPortable\Data\blog.db
    #driver-class-name: org.sqlite.JDBC
    #initialization-mode: always
    #username: admin
    #password: admin
  #jpa:
    #database-platform: com.example.springboot.utils.SQLDialect
    #hibernate:
      #ddl-auto: update
  #H2
  datasource:
    url: jdbc:h2:mem:blog
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

info:
  app:
    version: '@project.version@'
    artifactId: '@project.artifactId@'
    groupId: '@project.groupId@'
    description: '@project.description@'
  application:
    environment: dev

share:
  dir: C:\Users\jcastafe\Documents