server:
  port: 8080

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.springframework: info
    org.springframework.web: info
    springframework.web.client.RestTemplate: info
    org.springframework.security: info
    com.example: debug

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quarkus_test
    driverClassName: org.postgresql.Driver
    username: quarkus_test
    password: quarkus_test
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  redis:
    host: localhost
    port: 6379
    timeout: 60
  cache:
    type: redis
    redis:
        time-to-live: 30
        cache-null-values: false

info:
  app:
    version: '@project.version@'
    artifactId: '@project.artifactId@'
    groupId: '@project.groupId@'
    description: '@project.description@'
  application:
    environment: dev

share:
  dir: C:\Users\jcastafe\Documents